// Generated by CoffeeScript 1.6.1
(function() {
  var Bound, bound;

  Bound = (function() {

    function Bound(obj, el) {
      var key;
      this.attributes = {};
      this.frozen = false;
      this.el = el;
      for (key in obj) {
        if (obj[key]['value'] != null) {
          this.attributes[key] = obj[key];
        } else {
          this.attributes[key] = {
            value: obj[key]
          };
        }
      }
    }

    Bound.prototype.get = function(key) {
      return this.attributes[key]['value'];
    };

    Bound.prototype.set = function(key, value) {
      var $el, final;
      if (this.attributes[key] == null) {
        this.attributes[key] = {
          value: value
        };
      }
      this.attributes[key]['value'] = value;
      final = value;
      if (this.attributes[key]['handler'] != null) {
        final = this.attributes[key]['handler'](value);
      }
      if (!this.frozen) {
        $el = this.el.querySelector(".bound-" + key);
        return $el.textContent = final;
      }
    };

    Bound.prototype.render = function() {
      var key, _results;
      _results = [];
      for (key in this.attributes) {
        _results.push(this.set(key, this.attributes[key]['value']));
      }
      return _results;
    };

    Bound.prototype.freeze = function() {
      return this.frozen = !this.frozen;
    };

    return Bound;

  })();

  bound = function(obj, el) {
    if ((obj == null) || (el == null)) {
      throw new Error("bound - missing parameter");
    }
    return new Bound(obj, el);
  };

  module.exports = bound;

}).call(this);
